### ISSUE TITLE
Move content to wikis and display in website

### ISSUE THREAD

**Issue by VonSub** [Incubaid/www_incubaid#8]
We want to replace some mobirise parts of the website with content coming from the info_incubaid repo. We want to do so because then people without Mobirise can edit the .mds in the info_incubaid repo to change content easily.

Requirements:

- [x] Move content to info_incubaid repo
- [x] Figure out how to include a wiki page without the sidebar opened
- [x] Add < iframes > with corrosponding wikipage to mobirise website
- [x] Update Staging
- [x] Test Desktop
- [x] Test Mobile
- [ ] Sign off
- [ ] Merge to Production

**Comment by VonSub** [comment]
Exits, Current Projects, Former Projects, Introduction and About are moved to wiki .mds.

https://github.com/Incubaid/info_incubaid/tree/development/docs/webcontent

**Comment by ehab-hassan** [comment]
scroll need to fixed at mobile related to wiki issue(just for ifram part)
https://github.com/threefoldtech/OpenPublish/issues/18

**Comment by ehab-hassan** [comment]
scroll fixed

**Comment by VonSub** [comment]
@ehab-hassan as asked yesterday please fix the images all in same width and sharp.

**Comment by ehab-hassan** [comment]
All images resized to the same width

**Comment by VonSub** [comment]
sent to @despiegk for signoff
